# Generated by Django 3.2.12 on 2023-04-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('NI', 'NIKE'), ('AD', 'ADDIDAS')], default='', max_length=200),
            preserve_default=False,
        ),
    ]
