# Generated by Django 4.2.1 on 2023-05-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_order_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PA', 'PANT'), ('SH', 'SHOES'), ('TT', 'TSHIRT'), ('BG', 'BAG'), ('HA', 'HAT'), ('HO', 'HOODIE'), ('PH', 'PHONE')], max_length=200),
        ),
    ]
