# Generated by Django 4.2.1 on 2023-05-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='types_reports',
            field=models.CharField(choices=[('FI', 'FALSE INFO'), ('FK', 'FAKE PRODUCT')], default='', max_length=200),
            preserve_default=False,
        ),
    ]
