# Generated by Django 4.2.1 on 2023-06-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_report_types_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PA', 'PANT'), ('SH', 'SHOES'), ('TT', 'TSHIRT'), ('BG', 'BAG'), ('HA', 'HAT'), ('HO', 'HOODIE'), ('PH', 'PHONE'), ('JA', 'JACKETS')], max_length=200),
        ),
    ]
