# Generated by Django 4.2 on 2023-10-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='_id',
            field=models.CharField(blank=True, editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
