# Generated by Django 4.2 on 2023-11-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_order__id_alter_product__id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='firstName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='lastName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
