# Generated by Django 4.2 on 2023-11-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_shippingaddress_firstname_shippingaddress_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='appartment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
